### PR TITLE
Update translations version to 4.9.0

### PR DESCRIPTION
**Pull request by rmccar**
### What is the context of this PR?
Small PR to update eq-translations version to the latest released version of eq-translations (v4.9.0).

### How to review 
Check the change is to the correct version.

### CODE REVIEW

**Review by katie-gardner — APPROVED** [review]
running the poetry update myself I get a slightly different result with additional metadata and hyphen formatting instead of underscores, but checking online the understanding I've got is that this is fine and simply caused by me having a different version of poetry https://github.com/orgs/python-poetry/discussions/6949 - so all good from me

**Comment by rmccar** [comment]
> running the poetry update myself I get a slightly different result with additional metadata and hyphen formatting instead of underscores, but checking online the understanding I've got is that this is fine and simply caused by me having a different version of poetry https://github.com/orgs/python-poetry/discussions/6949 - so all good from me

Ive now updated it again so it might be closer to what you get now

**Comment by rmccar** [comment]
[Update eq-translations version](https://trello.com/c/UTgkU9qU/5714-update-eq-translations-version)

**Review by berroar — APPROVED** [review]
Seems to match the output I get when I install the new translations 👍

**Pull request merged**
